image: "python:3.8"


stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  allow_failure: true
  script:
  - python --version
  - pip install -r requirements.txt
  - pwd
  - ls -l
  - python -m mypy --ignore-missing-imports */*.py
  only:
    - merge_requests

flake8:
  stage: Static Analysis
  allow_failure: true
  script:
    - python --version
    - pip install -r requirements.txt
    - flake8 --max-line-length=120 */*.py
  only:
    - merge_requests

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - python --version
  - pip install -r requirements.txt
    - pylint -d C0301 */*.py
  only:
    - merge_requests

jsonlint:
  stage: Static Analysis
  allow_failure: true
  image: pipelinecomponents/jsonlint:latest
  script:
    -  packages/packages.json
  only:
    - merge_requests
lint_dockerfile:
  stage: Static Analysis
  allow_failure: true
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  only:
    - merge_requests
