

image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  script:
  - pwd
  - ls -l
  - python -m mypy */*.py
  only:
    - merge_requests

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 */*.py
 only:
    - merge_requests

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 */*.py
 only:
    - merge_requests
shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: Static Analysis
  before_script:
    - shellcheck --version
  script:
    - shellcheck ./*/*.sh
  only:
    - merge_requests

shfmt:
  image: mvdan/shfmt:v3.1.2-alpine
  stage: Static Analysis
  before_script:
    - shfmt -version
  script:
    - shfmt -i 2 -ci -d ./*/*.sh  # path to your shell scripts
  only:
    - merge_requests
