name: CI

on: 
  pull_request:
    branches: [ mainline, dev ]

jobs:
  buid_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - os: ubuntu:16.04
         - os: ubuntu:18.04
         - os: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install Dependcies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: script
        env:
          INSTANCE: ${{ matrix.os }}
        run: bash ./util/testing_build.sh
