name: CI

on: pull_request

jobs:
  latest:
    runs-on: ubuntu-22.04	
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install Dependcies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: script
        run: bash ./util/testing_build.sh
  focal_fossa:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install Dependcies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: script
        run: bash ./util/testing_build.sh
  bionic_beaver:
    runs-on: ubuntu-18.04	
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          
      - name: Install Dependcies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt"
      - name: script
        run: bash ./util/testing_build.sh
    
