name: CI

on: 
  pull_request:
    branches: [ mainline, dev ]

jobs:
  buid_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - os: ubuntu:16.04
         - os: ubuntu:18.04
         - os: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install poetry
        run: |
              python -m pip install poetry==1.4.0
      - name: Configure poetry
        run: |
              python -m poetry config virtualenvs.in-project true
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependcies
        run: |
            python -m poetry install

      - name: script
        env:
          INSTANCE: ${{ matrix.os }}
        run: bash ./util/testing_build.sh
